// NOF corridor membership without PostGIS (supersedes ADR 021, see ADR 028).
//
// The City publishes the corridors as polygons, so membership is point-in-polygon and needs no
// distance buffer at all. Python's 50 m ST_DWithin existed because the dataset it used was street
// centre-lines; that dataset has been withdrawn and its two documented ids both 404.
//
// The asset is regenerated by scripts/fetch_nof_corridors.py and bundled — 45 rings, ~83 KB
// gzipped — so a lookup costs no query and no network call.
import corridors from '../data/nof-corridors.json';

export interface CorridorMatch {
  corridor_name: string;
  corridor_type: 'eligible' | 'priority';
  is_priority: boolean;
}

interface Ring {
  t: number; // 1 = priority
  f: number; // FID within its layer
  b: number[]; // [minLng, minLat, maxLng, maxLat]
  r: number[][]; // outer ring, [lng, lat]
}

const RINGS = corridors.rings as Ring[];

// Ray casting. The ring is in degrees and a corridor spans far less than a degree, so treating
// lng/lat as planar introduces no error that matters at this scale.
function pointInRing(lng: number, lat: number, ring: number[][]): boolean {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    if (yi > lat !== yj > lat && lng < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}

// The City's layers carry no name attribute — only a FID — so the label names the layer and id.
function label(ring: Ring): string {
  return `${ring.t === 1 ? 'Priority' : 'Eligible'} corridor ${ring.f}`;
}

/**
 * Locate a point on the NOF corridors. Priority wins over eligible where they overlap, matching
 * Python's ORDER BY on corridor_type. Returns null off-corridor, which is the hard gate in
 * computeNofEligibility.
 */
export function locateCorridor(latitude: number | null, longitude: number | null): CorridorMatch | null {
  if (latitude === null || longitude === null) return null;

  let eligible: CorridorMatch | null = null;
  for (const ring of RINGS) {
    if (longitude < ring.b[0] || longitude > ring.b[2] || latitude < ring.b[1] || latitude > ring.b[3]) continue;
    if (!pointInRing(longitude, latitude, ring.r)) continue;
    if (ring.t === 1) return { corridor_name: label(ring), corridor_type: 'priority', is_priority: true };
    eligible = eligible ?? { corridor_name: label(ring), corridor_type: 'eligible', is_priority: false };
  }
  return eligible;
}

/** Provenance of the bundled asset, for the operations guide and for debugging a stale check. */
export const CORRIDOR_SOURCE = {
  generated_at: corridors.generated_at as string,
  ring_count: RINGS.length,
};
